#!/usr/bin/env ruby
# frozen_string_literal: true

require "fileutils"
require "yaml"

ROOT = File.expand_path("..", __dir__)
SPEC_PATH = File.join(ROOT, "openapi", "openapi.yaml")
GENERATED_DIR = File.join(ROOT, "lib", "licensekit", "generated")

def infer_auth(security)
  return "none" unless security.is_a?(Array) && !security.empty?

  security.each do |entry|
    next unless entry.is_a?(Hash)
    return "bearer" if entry.key?("bearerAuth")
    return "license" if entry.key?("licenseAuth")
  end

  "none"
end

def response_kind(response)
  return "empty" unless response.is_a?(Hash)

  content = response["content"]
  return "empty" unless content.is_a?(Hash)
  return "json" if content.key?("application/json")
  return "text" if content.key?("text/plain")

  "empty"
end

def error_response?(response)
  return false unless response.is_a?(Hash)
  return true if response["$ref"].is_a?(String)

  schema = response.dig("content", "application/json", "schema")
  schema.is_a?(Hash) && schema["$ref"] == "#/components/schemas/ErrorEnvelope"
end

def extract_success_responses(responses)
  entries = []
  return entries unless responses.is_a?(Hash)

  responses.each do |raw_status, response|
    status = Integer(raw_status, exception: false)
    next if status.nil?

    kind = response_kind(response)
    if status >= 200 && status < 300
      entries << [status, kind]
      next
    end

    next if error_response?(response)

    entries << [status, kind]
  end

  raise "operation is missing a successful response" if entries.empty?

  entries.sort_by(&:first)
end

def camel_to_snake(value)
  value.gsub(/(.)([A-Z][a-z]+)/, '\1_\2').gsub(/([a-z0-9])([A-Z])/, '\1_\2').downcase
end

def render_metadata(entries, surfaces)
  lines = [
    "# Generated by scripts/generate_from_openapi.rb. Do not edit manually.",
    "",
    "module LicenseKit",
    "  module Generated",
    "    OPERATION_METADATA = {"
  ]

  entries.each do |entry|
    success_pairs = entry[:success].map { |status, kind| "#{status} => #{kind.inspect}" }.join(", ")
    lines.concat(
      [
        "      #{entry[:operation_id].inspect} => {",
        "        method: #{entry[:method].inspect},",
        "        path: #{entry[:path].inspect},",
        "        auth: #{entry[:auth].inspect},",
        "        summary: #{entry[:summary].inspect},",
        "        success: { #{success_pairs} }",
        "      },"
      ]
    )
  end

  lines.concat(
    [
      "    }.freeze",
      "    MANAGEMENT_OPERATION_IDS = #{surfaces.fetch("management").map { |entry| entry[:operation_id] }.inspect}.freeze",
      "    RUNTIME_OPERATION_IDS = #{surfaces.fetch("runtime").map { |entry| entry[:operation_id] }.inspect}.freeze",
      "    SYSTEM_OPERATION_IDS = #{surfaces.fetch("system").map { |entry| entry[:operation_id] }.inspect}.freeze",
      "  end",
      "end",
      ""
    ]
  )
  lines.join("\n")
end

def render_scopes(entries)
  scopes = entries.flat_map { |entry| entry[:scopes] }.uniq.sort
  lines = [
    "# Generated by scripts/generate_from_openapi.rb. Do not edit manually.",
    "",
    "module LicenseKit",
    "  module Generated",
    "    OPERATION_SCOPES = {"
  ]

  entries.each do |entry|
    lines.concat(
      [
        "      #{entry[:operation_id].inspect} => {",
        "        method: #{entry[:method].inspect},",
        "        path: #{entry[:path].inspect},",
        "        scopes: #{entry[:scopes].inspect}.freeze",
        "      },"
      ]
    )
  end

  lines.concat(
    [
      "    }.freeze",
      "    MANAGEMENT_SCOPES = #{scopes.inspect}.freeze",
      "  end",
      "end",
      ""
    ]
  )
  lines.join("\n")
end

def render_surface_raw(class_name, entries)
  lines = [
    "  class #{class_name}",
    "    def initialize(client)",
    "      @client = client",
    "    end",
    ""
  ]

  entries.each do |entry|
    lines.concat(
      [
        "    # #{entry[:summary]}",
        "    def #{entry[:method_name]}(request = nil, options: nil, **kwargs)",
        "      @client.send(:perform_request_raw, #{entry[:operation_id].inspect}, request, options: options, **kwargs)",
        "    end",
        ""
      ]
    )
  end

  lines.concat(["  end", ""])
  lines
end

def render_surface(class_name, raw_class_name, entries, auth_type:, auth_value_name:)
  auth_line = auth_type == "none" ? '        auth_value: nil,' : "        auth_value: #{auth_value_name},"

  lines = [
    "  class #{class_name} < BaseClient",
    "    attr_reader :raw",
    "",
    "    def initialize(base_url:, #{auth_value_name}: nil, headers: nil, timeout: nil, user_agent: nil, retry_options: nil, transport: nil)"
  ]

  if auth_type == "none"
    lines[-1] = "    def initialize(base_url:, headers: nil, timeout: nil, user_agent: nil, retry_options: nil, transport: nil)"
  end

  lines.concat(
    [
      "      super(",
      "        base_url: base_url,",
      "        auth_type: #{auth_type.inspect},",
      auth_line,
      "        headers: headers,",
      "        timeout: timeout,",
      "        user_agent: user_agent,",
      "        retry_options: retry_options,",
      "        transport: transport",
      "      )",
      "      @raw = #{raw_class_name}.new(self)",
      "    end",
      ""
    ]
  )

  entries.each do |entry|
    lines.concat(
      [
        "    # #{entry[:summary]}",
        "    def #{entry[:method_name]}(request = nil, options: nil, **kwargs)",
        "      perform_request(#{entry[:operation_id].inspect}, request, options: options, **kwargs)",
        "    end",
        ""
      ]
    )
  end

  lines.concat(["  end", ""])
  lines
end

def render_clients(surfaces)
  lines = [
    "# Generated by scripts/generate_from_openapi.rb. Do not edit manually.",
    "",
    "module LicenseKit",
    ""
  ]

  lines.concat(render_surface_raw("ManagementRawClient", surfaces.fetch("management")))
  lines.concat(render_surface("ManagementClient", "ManagementRawClient", surfaces.fetch("management"), auth_type: "bearer", auth_value_name: "token"))
  lines.concat(render_surface_raw("RuntimeRawClient", surfaces.fetch("runtime")))
  lines.concat(render_surface("RuntimeClient", "RuntimeRawClient", surfaces.fetch("runtime"), auth_type: "license", auth_value_name: "license_key"))
  lines.concat(render_surface_raw("SystemRawClient", surfaces.fetch("system")))
  lines.concat(render_surface("SystemClient", "SystemRawClient", surfaces.fetch("system"), auth_type: "none", auth_value_name: "unused"))
  lines.concat(["end", ""])
  lines.join("\n")
end

document = YAML.safe_load(File.read(SPEC_PATH), aliases: true)
paths = document.fetch("paths", {})

metadata_entries = []
scope_entries = []
surface_entries = {
  "management" => [],
  "runtime" => [],
  "system" => []
}

paths.each do |pathname, path_item|
  next unless path_item.is_a?(Hash)

  path_item.each do |method, operation|
    next unless operation.is_a?(Hash)

    operation_id = operation["operationId"]
    next if operation_id.nil? || operation_id.empty?

    auth = infer_auth(operation["security"])
    summary = operation["summary"] || operation_id
    success_entries = extract_success_responses(operation["responses"])
    surface = auth == "bearer" ? "management" : auth == "license" ? "runtime" : "system"
    method_name = camel_to_snake(operation_id)

    metadata_entries << {
      operation_id: operation_id,
      method: method.to_s.upcase,
      path: pathname,
      auth: auth,
      summary: summary,
      success: success_entries,
      method_name: method_name
    }

    surface_entries.fetch(surface) << {
      operation_id: operation_id,
      method_name: method_name,
      summary: summary
    }

    required_scopes = operation["x-required-scopes"]
    next unless required_scopes.is_a?(Array)

    scope_entries << {
      operation_id: operation_id,
      method: method.to_s.upcase,
      path: pathname,
      scopes: required_scopes.map(&:to_s).sort
    }
  end
end

metadata_entries.sort_by! { |entry| entry[:operation_id] }
scope_entries.sort_by! { |entry| entry[:operation_id] }
surface_entries.each_value { |entries| entries.sort_by! { |entry| entry[:operation_id] } }

FileUtils.mkdir_p(GENERATED_DIR)
File.write(File.join(GENERATED_DIR, "metadata.rb"), render_metadata(metadata_entries, surface_entries))
File.write(File.join(GENERATED_DIR, "operation_scopes.rb"), render_scopes(scope_entries))
File.write(File.join(GENERATED_DIR, "clients.rb"), render_clients(surface_entries))
